#ifndef RENDER_QUEUE_H
#define RENDER_QUEUE_H

#include "DoubleBufferQueue.h"

namespace pxpk
{
	enum RenderType : std::uint8_t
	{
		RENDER_OBJ_ADD,
		RENDER_OBJ_REMOVE,
		RENDER_OBJ_CLEAR,
		RENDER_OBJ_LOAD_VERT,
		RENDER_OBJ_LOAD_INDEX,
		RENDER_OBJ_LOAD_COLOR,
		RENDER_OBJ_SET_COLOR,
		RENDER_OBJ_SET_POS,
		RENDER_OBJ_SET_ORIENT,
		RENDER_OBJ_SET_ORIENT_EULER,
		RENDER_OBJ_SET_SCALE,
		RENDER_OBJ_TRANSLATE,
		RENDER_OBJ_ROTATE,
		RENDER_OBJ_ROTATE_EULER,
		RENDER_OBJ_LOOKAT,
		RENDER_OBJ_DRAW,
		RENDER_CAM_ADD,
		RENDER_CAM_REMOVE,
		RENDER_CAM_CLEAR,
		RENDER_CAM_SET_POS,
		RENDER_CAM_SET_ORIENT,
		RENDER_CAM_SET_ORIENT_EULER,
		RENDER_CAM_TRANSLATE,
		RENDER_CAM_ROTATE,
		RENDER_CAM_ROTATE_EULER,
		RENDER_CAM_LOOKAT,
		RENDER_CAM_SET_FOV,
		RENDER_CAM_SET_NEAR,
		RENDER_CAM_SET_FAR
	};

	class RenderQueue : public pxpk::DoubleBuffferQueue
	{
		public:
	};
}

#endif  //  !RENDER_QUEUE_H